name: Testing
on:
  pull_request:
  push:
    paths:
      - 'packages/core'

jobs:
  lint:
    name: ESLint

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x', '20.x', '22.x']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Run tsc
        run: yarn tsc -build --noEmit
